#!/usr/bin/env bash
# Installs the repository's git hooks into .git/hooks/.
# Idempotent: safe to run multiple times.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOKS_DIR="$ROOT/.git/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
  echo "install-git-hooks: $HOOKS_DIR not found. Are you inside a git checkout?" >&2
  exit 1
fi

chmod +x "$ROOT/scripts/check-replit-secrets.sh"

HOOK="$HOOKS_DIR/pre-commit"
cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-git-hooks.sh — do not edit by hand.
exec "$(git rev-parse --show-toplevel)/scripts/check-replit-secrets.sh"
EOF
chmod +x "$HOOK"

echo "✓ Installed pre-commit hook: $HOOK"
echo "  It runs scripts/check-replit-secrets.sh on every commit."
echo "  Bypass (not recommended): git commit --no-verify"
